name: test
on: [push, pull_request]

jobs:
  test1:
    name: Run test 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache foo/bar directory
        uses: actions/cache@v2
        env:
          cache-name: cache-foobar2
        with:
          path: $HOME/foo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('README.md') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: echo
        run: |
          echo $HOME
          ls -al $HOME
          echo ${{ env.HOME }}
      - name: ls
        run: ls -al
      - name: Docker Compose
        run: docker-compose --version
      - name: touch baz
        run: date >> $HOME/foo/bar
      - name: cat baz
        run: cat $HOME/foo/bar
  test2:
    name: Run test 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose --version
  test3:
    name: Run test 3
    runs-on: ubuntu-latest
    needs: [test1, test2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose --hel
      - name: ls $HOME
        run: |
          pwd
          ls -al
          whoami
