name: test
on: [push, pull_request]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache foo/bar directory
        uses: actions/cache@v2
        env:
          cache-name: cache-foo
        with:
          path: foo/bar
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Docker Compose
        run: docker-compose --version
      - name: touch baz
        run: date >> foo/bar/baz
      - name: cat baz
        run: cat foo/bar/baz
